import Head from 'next/head';
import { Features, Footer, Hero, Testimonals } from '@/sections';
import { Header } from '@/components/header';
import { Box } from '@chakra-ui/react';

// todo: better SEO
export default function Home() {
	return (
		<>
			<Head>
				<title>BotMate</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Box position='relative'>
				<Box
					as='main'
					top={0}
					width='100%'
					height='900px'
					position='absolute'
					zIndex={-1}
					bgGradient='linear(to-t, primary.dark, #0f112c)'
				/>
				<Header />
				<Hero />
				<Features />
				<Testimonals />
				<Footer />
			</Box>
		</>
	);
}
