import Head from 'next/head';
import { Hero } from '@/sections';
import { Header } from '@/components/header';
import { Box } from '@chakra-ui/react';

export default function Home() {
	return (
		<>
			<Head>
				<title>BotMate</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Box as='main' bgGradient='linear(to-t, primary.dark, #0f112c)'>
				<Header />
				<Hero />
			</Box>
		</>
	);
}
